//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/ControlMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlMaster : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlMaster"",
    ""maps"": [
        {
            ""name"": ""Player 1"",
            ""id"": ""24a12d97-2828-4118-bf72-fab9695c0692"",
            ""actions"": [
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""785f0aaf-8d0a-4225-ae83-d599d136635b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""14cf3de4-b670-452b-8207-469f433e150c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rotate"",
                    ""type"": ""Value"",
                    ""id"": ""b83e641c-28bb-4b63-8ad0-04bf3a54aff8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""grabAll"",
                    ""type"": ""Button"",
                    ""id"": ""cb499202-af1d-4f14-9787-07bc359d4211"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""grabL"",
                    ""type"": ""Button"",
                    ""id"": ""523ec919-f7e5-4024-998f-a4284a659852"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""grabR"",
                    ""type"": ""Button"",
                    ""id"": ""5c449f65-263f-4db6-a7c4-6c4b934505d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""arm"",
                    ""type"": ""Button"",
                    ""id"": ""d3191ad7-d279-4981-9b97-4504f07b3715"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""slowmode"",
                    ""type"": ""Button"",
                    ""id"": ""a161c023-46ed-420c-be6f-7dfacd4eb5f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Axons"",
                    ""type"": ""Button"",
                    ""id"": ""bf73ae25-89a8-43b8-b6e6-b1fe672a7907"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""slides"",
                    ""type"": ""Value"",
                    ""id"": ""c03ed406-b9e4-4c22-a412-1b8c0ffa4597"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f25aed7c-d330-4430-9f27-e3356cc85d29"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0b2d4931-ffdf-417e-adf3-da75f2668733"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""099b7559-e7e8-4e4e-8898-6777644d06dd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a67cdbbb-e0af-46c8-b576-6ff73fd8385c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""06c97fb2-e83d-4c23-a00c-b9c7947b4379"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""01d9b9c0-fa1c-408c-8971-f3dba38f93af"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f9aa3f78-466c-41d9-8463-73f76975a499"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a0d6003-ee32-4134-9c3c-8f059c053e29"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""845f183e-3e99-4f77-923d-d75ba1301fda"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f97e1263-fe6b-4ff7-8444-978cbec6f33c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f12096ed-c69c-4ab8-9a08-0dc5da7cadd9"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""57553add-ea8e-4c5a-8054-6c6f146b2602"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""02c4de99-6cf3-47c2-9a20-ee5e2cc52e8e"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""10099bc8-c234-424c-b782-2ff189630ff5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ca3c95ba-4438-405f-bb22-ebce18b479c5"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d901a3ec-e7cc-4f05-ac41-e45ac8b56f84"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2f25b712-3e38-4cbc-b934-4d0a9a3c651f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""513bc439-0300-465b-b46b-4667798d73d2"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""994b1948-c858-46d7-94da-4fc8f14539d1"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""grabAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d8d2a1d-7b39-4ab7-b3e3-165d292ebde3"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""grabAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73e1a9df-a541-42f6-b7ef-7a09c8bdf286"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""grabL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b11842c-5c9b-4593-af01-515861e576f2"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""grabL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8d46c7f-cdcb-4cf6-874d-b8e92ade36c5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""grabR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e13edb47-e744-4056-9437-2f3a3c4591d0"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""grabR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5552b95-7920-4f1a-a414-264dede14535"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""arm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e764cab-7a6f-4ea1-aa99-cdcd1ab2c7f9"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""slowmode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20424db2-79cf-482b-94e4-1bdb89edaaa2"",
                    ""path"": ""<Keyboard>/rightCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""slowmode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1de0d8f-6cf2-4a40-a957-97d4bae52d4b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axons"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ea32b8b8-6b1c-4015-ab4a-796652be64db"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""slides"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1ba40a03-2de9-4236-b2f3-c9ec4af8cf65"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""slides"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8d3da9ac-5db0-42df-9c7b-b629d80a33f5"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""slides"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3d206a90-3442-455b-b894-716839e0b326"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""slides"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cbfe729d-2e10-41d6-b35d-86471b23d191"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""8BitDo (XBOX Bluetooth)"",
                    ""action"": ""slides"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""8BitDo (XBOX Bluetooth)"",
            ""bindingGroup"": ""8BitDo (XBOX Bluetooth)"",
            ""devices"": [
                {
                    ""devicePath"": ""<XboxOneGampadiOS>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XboxOneGamepadAndroid>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""New control scheme"",
            ""bindingGroup"": ""New control scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player 1
        m_Player1 = asset.FindActionMap("Player 1", throwIfNotFound: true);
        m_Player1_move = m_Player1.FindAction("move", throwIfNotFound: true);
        m_Player1_Reset = m_Player1.FindAction("Reset", throwIfNotFound: true);
        m_Player1_rotate = m_Player1.FindAction("rotate", throwIfNotFound: true);
        m_Player1_grabAll = m_Player1.FindAction("grabAll", throwIfNotFound: true);
        m_Player1_grabL = m_Player1.FindAction("grabL", throwIfNotFound: true);
        m_Player1_grabR = m_Player1.FindAction("grabR", throwIfNotFound: true);
        m_Player1_arm = m_Player1.FindAction("arm", throwIfNotFound: true);
        m_Player1_slowmode = m_Player1.FindAction("slowmode", throwIfNotFound: true);
        m_Player1_Axons = m_Player1.FindAction("Axons", throwIfNotFound: true);
        m_Player1_slides = m_Player1.FindAction("slides", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player 1
    private readonly InputActionMap m_Player1;
    private IPlayer1Actions m_Player1ActionsCallbackInterface;
    private readonly InputAction m_Player1_move;
    private readonly InputAction m_Player1_Reset;
    private readonly InputAction m_Player1_rotate;
    private readonly InputAction m_Player1_grabAll;
    private readonly InputAction m_Player1_grabL;
    private readonly InputAction m_Player1_grabR;
    private readonly InputAction m_Player1_arm;
    private readonly InputAction m_Player1_slowmode;
    private readonly InputAction m_Player1_Axons;
    private readonly InputAction m_Player1_slides;
    public struct Player1Actions
    {
        private @ControlMaster m_Wrapper;
        public Player1Actions(@ControlMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @move => m_Wrapper.m_Player1_move;
        public InputAction @Reset => m_Wrapper.m_Player1_Reset;
        public InputAction @rotate => m_Wrapper.m_Player1_rotate;
        public InputAction @grabAll => m_Wrapper.m_Player1_grabAll;
        public InputAction @grabL => m_Wrapper.m_Player1_grabL;
        public InputAction @grabR => m_Wrapper.m_Player1_grabR;
        public InputAction @arm => m_Wrapper.m_Player1_arm;
        public InputAction @slowmode => m_Wrapper.m_Player1_slowmode;
        public InputAction @Axons => m_Wrapper.m_Player1_Axons;
        public InputAction @slides => m_Wrapper.m_Player1_slides;
        public InputActionMap Get() { return m_Wrapper.m_Player1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player1Actions set) { return set.Get(); }
        public void SetCallbacks(IPlayer1Actions instance)
        {
            if (m_Wrapper.m_Player1ActionsCallbackInterface != null)
            {
                @move.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnMove;
                @move.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnMove;
                @move.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnMove;
                @Reset.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnReset;
                @Reset.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnReset;
                @Reset.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnReset;
                @rotate.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRotate;
                @rotate.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRotate;
                @rotate.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRotate;
                @grabAll.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabAll;
                @grabAll.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabAll;
                @grabAll.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabAll;
                @grabL.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabL;
                @grabL.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabL;
                @grabL.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabL;
                @grabR.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabR;
                @grabR.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabR;
                @grabR.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabR;
                @arm.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnArm;
                @arm.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnArm;
                @arm.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnArm;
                @slowmode.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSlowmode;
                @slowmode.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSlowmode;
                @slowmode.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSlowmode;
                @Axons.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnAxons;
                @Axons.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnAxons;
                @Axons.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnAxons;
                @slides.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSlides;
                @slides.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSlides;
                @slides.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSlides;
            }
            m_Wrapper.m_Player1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @move.started += instance.OnMove;
                @move.performed += instance.OnMove;
                @move.canceled += instance.OnMove;
                @Reset.started += instance.OnReset;
                @Reset.performed += instance.OnReset;
                @Reset.canceled += instance.OnReset;
                @rotate.started += instance.OnRotate;
                @rotate.performed += instance.OnRotate;
                @rotate.canceled += instance.OnRotate;
                @grabAll.started += instance.OnGrabAll;
                @grabAll.performed += instance.OnGrabAll;
                @grabAll.canceled += instance.OnGrabAll;
                @grabL.started += instance.OnGrabL;
                @grabL.performed += instance.OnGrabL;
                @grabL.canceled += instance.OnGrabL;
                @grabR.started += instance.OnGrabR;
                @grabR.performed += instance.OnGrabR;
                @grabR.canceled += instance.OnGrabR;
                @arm.started += instance.OnArm;
                @arm.performed += instance.OnArm;
                @arm.canceled += instance.OnArm;
                @slowmode.started += instance.OnSlowmode;
                @slowmode.performed += instance.OnSlowmode;
                @slowmode.canceled += instance.OnSlowmode;
                @Axons.started += instance.OnAxons;
                @Axons.performed += instance.OnAxons;
                @Axons.canceled += instance.OnAxons;
                @slides.started += instance.OnSlides;
                @slides.performed += instance.OnSlides;
                @slides.canceled += instance.OnSlides;
            }
        }
    }
    public Player1Actions @Player1 => new Player1Actions(this);
    private int m__8BitDoXBOXBluetoothSchemeIndex = -1;
    public InputControlScheme _8BitDoXBOXBluetoothScheme
    {
        get
        {
            if (m__8BitDoXBOXBluetoothSchemeIndex == -1) m__8BitDoXBOXBluetoothSchemeIndex = asset.FindControlSchemeIndex("8BitDo (XBOX Bluetooth)");
            return asset.controlSchemes[m__8BitDoXBOXBluetoothSchemeIndex];
        }
    }
    private int m_NewcontrolschemeSchemeIndex = -1;
    public InputControlScheme NewcontrolschemeScheme
    {
        get
        {
            if (m_NewcontrolschemeSchemeIndex == -1) m_NewcontrolschemeSchemeIndex = asset.FindControlSchemeIndex("New control scheme");
            return asset.controlSchemes[m_NewcontrolschemeSchemeIndex];
        }
    }
    public interface IPlayer1Actions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnGrabAll(InputAction.CallbackContext context);
        void OnGrabL(InputAction.CallbackContext context);
        void OnGrabR(InputAction.CallbackContext context);
        void OnArm(InputAction.CallbackContext context);
        void OnSlowmode(InputAction.CallbackContext context);
        void OnAxons(InputAction.CallbackContext context);
        void OnSlides(InputAction.CallbackContext context);
    }
}
